### ISSUE TITLE
zoom automatique

### ISSUE THREAD

**Issue by ghost** [pierreporte/bornographe#1]
Par défaut je pense qu'il faut bloquer la taille par rapport à la résolution de l'écran, en fait j'ai réussi en quelques manipulations à faire exploser le cadre

**Comment by pierreporte** [comment]
J’ai du mal à comprendre ce qui ne va pas. Une capture d’écran aiderait.

**Comment by ghost** [comment]
On voit qu'on explose assez facilement le cadre

![capture du 2016-12-11 12-10-24](https://cloud.githubusercontent.com/assets/3888577/21079716/dd31eb7c-bf9a-11e6-9ff8-b9d588502a94.png)

**Comment by pierreporte** [comment]
D’accord, je vais voir comment régler ça.

**Comment by pierreporte** [comment]
J’ai résolu le problème en donnant à la fenêtre une taille fixe. Ainsi, quelle que soit la taille du repère, il n’y aura plus de débordement. On peut toujours redimensionner la fenêtre ou la maximiser, au besoin.
