### ISSUE TITLE
Enregistrement en png se fait en svg, lorsque l'on ne met pas l'extension dans le fichier

### ISSUE THREAD

**Issue by durandarno** [pierreporte/bornographe#11]
Bonjour,
J'ai tenté d'enregistrer en png,j'ai choisi donc png et j'ai mis "repere" en nom de fichier pensant que l'extension allait se mettre automatiquement, or en fait, il a enregistré en svg.
J'ai testé en mettant png, et en précisant "repere.png" en nom de fichier, là il a bien enregistré en png.

**Comment by pierreporte** [comment]
Quelle version avez-vous essayé, précisément ? Indiquez le numéro du commit. Avez-vous bien sélectionné « Image PNG (*.png) » dans la liste déroulante ?

**Comment by durandarno** [comment]
Au temps pour moi, j'ai cru prendre le bon executable... Navré pour ce faux bug.
