### ISSUE TITLE
Erreur python

### ISSUE THREAD

**Issue by ghost** [pierreporte/bornographe#14]
A l'exécution :

    cyrille@cyrille-fixe:~/bornrep-master$ python bornrep.py
      File "bornrep.py", line 4
    SyntaxError: Non-ASCII character '\xc3' in file bornrep.py on line 4, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by pierreporte** [comment]
Il faut utiliser Python 3 et pas Python 2. Réessaie avec la commande `python3`.

De plus, il vaut mieux exécuter la commande `./bornrep.py` après avoir pris soin de rendre le fichier exécutable.

**Comment by ghost** [comment]
confirmé
