### ISSUE TITLE
Les valeurs numériques entrées au clavier ne sont pas prises en compte

### ISSUE THREAD

**Issue by ghost** [pierreporte/bornographe#2]
La génération ne donne rien suite à une modification de la longueur totale.

**Comment by pierreporte** [comment]
J’ai besoin de plus de détails. Chez moi, lorsque je coche une des lignes « longueur totale » et que je modifie la valeur, la longueur est mise à jour une fois que j’ai cliqué sur « Générer ».

Édit. — Je viens de voir que tu sembles n’avoir ce problème que pour l’axe des ordonnées, mais chez moi ça marche parfaitement.

**Comment by ghost** [comment]
Pour l'axe des ordonnées, pour longueur totale, si je mets une valeur, 5, 10, 15 ou 20 cm, la génération ne change pas la taille. Ce problème ne se pose pas pour l'axe des abscisses.

**Comment by pierreporte** [comment]
C’est étrange. Voici ce que l’obtiens pour une longueur totale de 5 cm :

![bornographe_546](https://cloud.githubusercontent.com/assets/2029853/21079816/dcef9a94-bf9d-11e6-8581-e0c32043c0f9.png)

En mesurant sur l’écran, ça semble correct. Quelle que soit la longueur totale, j’ai le bon résultat.

**Comment by ghost** [comment]
j'ai trouvé le bug, je fais la saisie direct au clavier, je fais générer, il ne le prend pas, je le fais à la souris en cliquant sur les flèches haut bas ça prend.

**Comment by pierreporte** [comment]
Oui, effectivement.

**Comment by pierreporte** [comment]
Le problème a été résolu. Les longueurs sont mises à jours soit en changeant le type de longueur (pour n’importe quel axe : je n’ai pas fait la distinction), soit en appuyant sur <kbd>Entrée</kbd> lorsque le champ de saisie a le focus.
